### ISSUE TITLE
Include all dependencies

### ISSUE THREAD

**Issue by 17o2** [daaguirr/Ivoox-Downloader#3]
Using Python 3.7.4 in a freshly createt venv, after installing the package , and installing `beautifulsoup4`, I get the following error:
```
ModuleNotFoundError: No module named 'requests'
```
This is solved by running
```
pip3 install requests
```

After that, I got
```
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
```
which was solved by running
```
pip3 install html5lib
```

This made it work! 🎉

Please consider adding these modules to the dependency list for a better installation experience.
Thanks for this nifty tool!

**Comment by daaguirr** [comment]
Hi, added !
